name: isolate_task_queue
description: A package for isolate and for task-queue.
version: 1.0.1
repository: https://github.com/mikes222/isolate_task_queue

environment:
  sdk: '>=3.1.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.28.0

dev_dependencies:
  lints: ^6.0.0

  test: ^1.26.2
