name: isolate_task_queue
description: A package for isolate and for task-queue.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.28.0

dev_dependencies:
  lints: ^6.0.0

  test: ^1.26.2
